layout_spectrum: 0.2794209214474195
typography_spectrum: 0.7516662826286721
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#63422F'
    - '#24AE4B'
    - '#757A7F'
  brandStrength: 0.4511611909416532
  lightness: 0.6608908694559285
  saturation: 0.2520743561539762
  rhythmicContrast: 0.40339921099816145
name: ehtest
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: '<img src="https://easyhire.me/images/landing/demonstration.jpg">'
    src: 'https://easyhire.me/images/landing/demonstration.jpg'
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://easyhire.me'
        name: Easyhire
        favicon: null
        domain: easyhire.me
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: 'https://easyhire.me/images/landing/demonstration.jpg'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ecfbd85d-60b0-443a-9f3c-0b533b85c473.svg
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/819bd19a-cad8-4ac7-aa8c-7911a36a8be8.svg
purpose:
  - type: contact
    url: 'mailto:aaron.schutjer@gmail.com'
    label: Contact me
title: Work Portfolio
description: ''
